DROP TABLE IF EXISTS `movie`;
CREATE TABLE `movie`(
`Id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
`Title` VARCHAR(30) NOT NULL,
`Director` VARCHAR(30) NOT NULL,
`Genre` VARCHAR(20) NOT NULL,
`Language` VARCHAR(20) NOT NULL,
PRIMARY KEY(`Id`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(50) NOT NULL,
  `password` char(32) NOT NULL,
  `username` varchar(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;